# Generated by Django 6.0.1 on 2026-01-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='agent_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
