# Generated by Django 6.0.2 on 2026-02-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_agent_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='agent_log',
            field=models.TextField(blank=True, default='English'),
            preserve_default=False,
        ),
    ]
