# Generated by Django 6.0.2 on 2026-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_language_alter_blog_agent_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='generation_time',
            field=models.FloatField(default=0),
        ),
    ]
